namespace Daynote.App.Localization;

/// <summary>
/// The English string catalog. Mirrors <see cref="KoreanStrings"/> key-for-key — a parity test
/// fails if either catalog gains a key the other lacks, or if a format string's <c>{0}</c>
/// placeholders do not match across the two. Format strings use <c>{0}</c> placeholders.
/// </summary>
internal static class EnglishStrings
{
    internal static IReadOnlyDictionary<string, string> Values { get; } = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        // Command region
        ["SearchHint"] = "Search notes",
        ["SearchAutomation"] = "Search notes",
        ["Settings"] = "Settings",
        ["OpenSettings"] = "Open settings",

        // Capture state (command-row chip, tray, settings)

        // Sidebar
        ["Today"] = "Today",
        ["GoToToday"] = "Go to today",
        ["AddNote"] = "Add note",
        ["PreviousMonth"] = "Previous month",
        ["NextMonth"] = "Next month",
        ["CalendarMonth"] = "Calendar month",
        ["SidebarNoteList"] = "Sidebar note list",
        ["MiniCalendar"] = "Mini month calendar",
        ["MoveNoteUpFormat"] = "Move {0} up",
        ["MoveNoteDownFormat"] = "Move {0} down",

        // Note region
        ["DateHeadingAutomation"] = "Selected date heading",
        ["OrderedNoteTabs"] = "Note tabs",
        ["MarkdownEditor"] = "Markdown editor",
        ["CloseNoteFormat"] = "Close {0}",
        ["EditorEmptyHint"] = "Start today's first entry",

        // Editor toolbar
        ["EditorToolbar"] = "Editor toolbar",
        ["SaveStatusAutomation"] = "Save status",
        ["FormattingCommands"] = "Markdown formatting commands",
        ["Bold"] = "Bold",
        ["Italic"] = "Italic",
        ["BulletedList"] = "Bulleted list",
        ["NumberedList"] = "Numbered list",
        ["InlineCode"] = "Inline code",

        // Save status text
        ["SaveDirty"] = "Unsaved",
        ["SaveSaving"] = "Saving",
        ["SaveSaved"] = "Saved",
        ["SaveFailed"] = "Save failed",
        ["Retry"] = "Retry",
        ["RetrySave"] = "Retry save",

        // Clipboard drawer
        ["Delete"] = "Delete",

        // Search
        ["SearchResultsOverlay"] = "Search results overlay",
        ["SearchSummary"] = "Search summary",
        ["SearchQuery"] = "Search query",
        ["SearchResultCount"] = "Search result count",
        ["SearchScope"] = "Search scope",
        ["SearchScopeValue"] = "Notes and files",
        ["SearchLoadingAutomation"] = "Searching",
        ["SearchLoading"] = "Searching…",
        ["SearchEmptyAutomation"] = "No search results",
        ["SearchEmpty"] = "No notes match your search.",
        ["SearchErrorAutomation"] = "Search error",
        ["SearchError"] = "Search is unavailable. Try again once storage is available.",
        ["SearchResults"] = "Search results",
        ["SearchResultSnippet"] = "Result preview",
        ["ResultDate"] = "Result date",
        ["NoteSource"] = "Note item",
        ["ClipboardSourceLabel"] = "File item",
        ["SearchKindNote"] = "Note",
        ["SearchKindClipboard"] = "File",
        ["StaleSearchResult"] = "That result is no longer available. The search results have been refreshed.",
        ["StaleSearchResultAutomation"] = "Stale search result",
        ["SearchNoResults"] = "No results",
        ["SearchUnavailableShort"] = "Search unavailable",
        ["SearchResultsShownFormat"] = "Showing {0} results",
        ["SearchResultsCountFormat"] = "{0} results",
        ["SearchResultsCountFormatOne"] = "{0} result",

        // Settings
        ["SettingsTitle"] = "Settings",
        ["CloseSettings"] = "Close settings",
        ["SettingsStartupRow"] = "Run at Windows startup",
        ["SettingsStartupLabel"] = "Start Daynote when I sign in",
        ["SettingsStartupAutomation"] = "Start Daynote at sign-in",
        ["SettingsStorageRow"] = "Storage location",
        ["SettingsStorageLabel"] = "Storage location",
        ["SettingsPrivacyRow"] = "Privacy",
        ["SettingsPrivacyLabel"] = "Privacy",
        ["SettingsStartupEnabledText"] = "Daynote starts automatically when you sign in.",
        ["SettingsStartupDisabledText"] = "Daynote does not start automatically.",
        ["SettingsStartupEnabledByPolicyText"] = "Set by administrator policy and cannot be changed here.",
        ["SettingsStartupDisabledByPolicyText"] = "Disabled by administrator policy and cannot be changed here.",
        ["SettingsStartupDisabledByUserText"] = "Turned off in Windows startup app settings. Re-enable it there.",
        ["SettingsStartupUnavailableText"] = "Startup app settings are unavailable on this device.",
        ["SettingsPrivacyText"] =
            "Notes are stored in a plain-text SQLite database on this PC, and attachments as local " +
            "files. Daynote itself has no analytics and no telemetry.",
        ["SettingsPrivacyMcp"] =
            "If you register the AI integration (MCP), the AI client you connect can read and write " +
            "your notes, and that client may send their content to its own service.",
        ["SettingsPrivacySync"] =
            "Cloud sync is off by default. When you sign in, notes are encrypted on this PC before they are uploaded.",

        // AI integration / MCP (settings)
        ["SettingsMcpRow"] = "AI integration",
        ["SettingsMcpLabel"] = "AI integration (MCP)",
        ["SettingsMcpDesc"] =
            "Let AI tools like Claude read and write your Daynote notes directly. The MCP server is " +
            "installed alongside Daynote, so one button registers it - nothing to build or download.",
        ["SettingsMcpRegister"] = "Register with Claude Desktop",
        ["SettingsMcpRegistered"] = "Registered. Restart Claude Desktop and the daynote tools appear.",
        ["SettingsMcpAlreadyRegistered"] = "Already registered.",
        ["SettingsMcpFailedFormat"] = "Registration failed. Please check the config file yourself: {0}",
        ["SettingsMcpUnavailable"] =
            "This build has no MCP server to register. The feature ships with Daynote installed from the Microsoft Store.",
        ["SettingsMcpCodeHint"] = "For Claude Code, run this one line in a terminal instead.",
        ["SettingsMcpFooter"] =
            "Tools provided: search, by-date, recent list, create, update, delete. See docs/MCP.md for details.",
        ["SettingsMcpCopy"] = "Copy",
        ["SettingsMcpCopied"] = "Copied!",

        // Shortcuts (settings)
        ["SettingsShortcutsRow"] = "Shortcuts",
        ["SettingsSummonHotkeyLabel"] = "Global summon shortcut",
        ["SettingsSummonHotkeyDesc"] =
            "Press this combination from anywhere to bring the window straight up, even while Daynote is hidden in the tray.",
        ["HotkeyChange"] = "Change",
        ["HotkeyCapturing"] = "Press a key combination…",
        ["HotkeyConflict"] = "Another app is already using that combination. Pick a different one.",
        ["HotkeyInvalid"] = "Press a modifier (Ctrl/Alt/Shift/Win) together with a regular key.",
        ["HotkeyReset"] = "Default",
        ["SettingsInAppShortcutsLabel"] = "In-app shortcuts",

        // File links (body paste/drop)
        ["PastedImagePrefix"] = "Image",

        // Backup / restore (settings)
        ["SettingsBackupRow"] = "Backup and restore",
        ["SettingsBackupLabel"] = "Back up and restore your data",
        ["SettingsBackupDesc"] =
            "Back up every note, attachment, and setting to a single zip file, or restore from a backup file.",
        ["BackupButton"] = "Back up",
        ["RestoreButton"] = "Restore",
        ["BackupInProgress"] = "Backing up…",
        ["BackupSucceeded"] = "Backup complete.",
        ["BackupFailed"] = "Backup failed. Check the destination location.",
        ["BackupFlushBlocked"] = "There are unsaved changes, so the backup cannot run. Resolve the save problem first.",
        ["RestoreStagedRestarting"] =
            "The restore is staged. It will be applied the next time the app starts. (Your current data is kept in the pre-restore-backup folder.)",
        ["RestoreIncompatible"] = "This backup was made by a newer version and cannot be restored.",
        ["RestoreInvalid"] = "That is not a valid Daynote backup file.",
        ["RestoreFailed"] = "Staging the restore failed.",

        // In-app shortcut action labels
        ["ShortcutNewNote"] = "New note",
        ["ShortcutGoToday"] = "Go to today",
        ["ShortcutSettings"] = "Open/close settings",
        ["ShortcutToggleTheme"] = "Toggle theme",
        ["ShortcutToggleLeft"] = "Collapse/expand left panel",
        ["ShortcutToggleRight"] = "Collapse/expand right panel",
        ["ShortcutOpenSticky"] = "Pop out as a sticky note",
        ["ShortcutQuickSticky"] = "New sticky note for today (global)",

        // Onboarding tutorial
        ["TutorialBack"] = "Back",
        ["TutorialNext"] = "Next",
        ["TutorialSkip"] = "Skip",
        ["TutorialFinish"] = "Get started",
        ["TutorialProgressFormat"] = "{0} / {1}",

        ["TutorialWelcomeTitle"] = "Welcome to Daynote",
        ["TutorialWelcomeBody"] = "A desktop app for writing and organizing notes by date. Here's a quick tour.",

        ["TutorialNotesTitle"] = "Notes and the calendar",
        ["TutorialNotesBody"] = "Pick a date in the calendar on the left and write in the middle. The + button adds a note, and everything saves as you type.",

        ["TutorialTodoTitle"] = "To-do checkboxes",
        ["TutorialTodoBody"] = "Type -[] in the body to make a checkbox, and add a due time like (7/25 14:00). They gather by date in the To-do tab on the right.",

        ["TutorialFavoritesTitle"] = "Favourites",
        ["TutorialFavoritesBody"] = "The star next to the title marks a note as a favourite. They gather in the Favourites tab on the right, whatever their date, so the notes you keep coming back to are one click away.",

        ["TutorialTagsTitle"] = "Tags",
        ["TutorialTagsBody"] = "Type a word into '+ Tag' under the title to tag the note. The Tags tab on the right groups notes by tag, and clicking one takes you to that note.",

        ["TutorialFilesTitle"] = "Attachments and body links",
        ["TutorialFilesBody"] = "Drop files onto the Files tab, or paste an image or file into the body — it is stored as a file and only a link stays in the text. Click the link to open it in the Files tab.",

        ["TutorialStickyTitle"] = "Sticky notes",
        ["TutorialStickyBody"] = "Pop a note out into a sticky window and pin it above everything else. The sticky note and the body edit together in real time.",

        ["TutorialSearchTitle"] = "Unified search",
        ["TutorialSearchBody"] = "Search titles, bodies, and files at once. Results highlight the part your keyword matched.",

        ["TutorialShortcutsTitle"] = "Shortcuts",
        ["TutorialShortcutsBody"] = "Reach what you use most with a keystroke. Global shortcuts work even while the app sits in the tray, and in-app shortcuts can be changed in settings.",

        ["TutorialWrapTitle"] = "Backup and settings",
        ["TutorialWrapBody"] = "Open settings from the account button at the right of the title bar, the tray menu, or Ctrl+,. Manage data backup and restore, shortcuts, and startup options there.",

        ["TutorialClosingTitle"] = "Ready when you are",
        ["TutorialClosingBody"] =
            "We left a sample note on today's date. Feel free to change it or delete it as you find your way around. " +
            "You can reopen this tour any time from Settings → Help. Enjoy Daynote!",

        // Sample note seeded on first run (dated to-dos use today's month/day via {0}/{1}).
        ["SampleNoteTitle"] = "Today's work notes (sample)",
        ["SampleNoteBodyFormat"] =
            "Here is one way to use Daynote. This note is only an example — delete it whenever you like.\n\n" +
            "-[] Write up the morning team standup ({0}/{1} 10:00)\n" +
            "-[x] Review last week's status report\n" +
            "-[] Send the reply to the client ({0}/{1} 15:00)\n\n" +
            "[Meeting notes]\n" +
            "- Shared the release schedule for the new feature\n" +
            "- Re-prioritized three QA issues\n\n" +
            "Tip: pasting a file into the body stores it in the Files tab and leaves a link behind. " +
            "Use the search box at the top to find anything across all your notes.",

        ["TutorialShortcutSummon"] = "Summon Daynote from anywhere (global)",
        ["TutorialShortcutQuickSticky"] = "New sticky note for today (global)",

        ["SettingsTutorialRow"] = "Help",
        ["SettingsTutorialLabel"] = "How-to tour",
        ["SettingsTutorialButton"] = "Replay the tour",

        // About / author (settings)
        ["SettingsAboutRow"] = "Author",
        ["SettingsAboutLabel"] = "Author",
        ["AuthorName"] = "Withcube",
        ["AuthorEmail"] = "aracube@gmail.com",

        // Tray menu
        ["TrayAppName"] = "Daynote",
        ["TrayShow"] = "Show Daynote",
        ["TraySettings"] = "Settings",
        ["TrayQuit"] = "Quit",

        // Calendar automation suffix
        ["TodaySuffix"] = ", today",

        // ── Redesign (calendar-notes.dc.html, DESIGN.md Revision 2026-07-21) ──
        ["AppTitle"] = "Calendar Notes",
        ["UnifiedSearchHint"] = "Search everything — notes, files, dates",
        ["ClearSearch"] = "Clear search",
        ["ThemeToggle"] = "Toggle theme",
        ["SidebarsExpand"] = "Expand sidebars",
        ["SidebarsCollapse"] = "Collapse sidebars",
        ["TabTodoName"] = "To-do tab",
        ["TabFilesName"] = "Files tab",
        ["WindowMinimize"] = "Minimize",
        ["WindowMaximize"] = "Maximize",
        ["WindowRestore"] = "Restore down",
        ["WindowClose"] = "Close",

        // Timeline view mode
        ["TimelineToggle"] = "Timeline view",
        ["TimelineExpand"] = "Expand",
        ["TimelineCollapse"] = "Collapse",
        // ── Desktop (design B) ─────────────────────────────────────────────────────────────────
        ["DeskSearch"] = "Search",
        ["DeskNavToday"] = "Today's notes",
        ["DeskNavTimeline"] = "Timeline",
        ["DeskNavTodo"] = "To-dos",
        ["DeskNavFavorites"] = "Favorites",
        ["DeskNavTags"] = "Tags",
        ["DeskNavFiles"] = "Files",
        ["DeskHeaderMonthWeekdayFormat"] = "MMMM · dddd",
        ["DeskHeaderYearFormat"] = "yyyy",
        ["DeskGoTodayTipFormat"] = "Go to today ({0})",
        ["DeskTimelineButton"] = "Timeline",
        ["DeskDayPanelTipFormat"] = "Day panel ({0})",
        ["DeskThemeTipFormat"] = "Switch theme ({0})",
        ["DeskNewNoteTipFormat"] = "New note ({0})",
        ["DeskSidebarCollapseTipFormat"] = "Collapse sidebar ({0})",
        ["DeskTitlePlaceholder"] = "Title",
        ["DeskPostItTipFormat"] = "Open as a sticky note ({0})",
        ["DeskCharLineFormat"] = "{0} characters · {1} lines",
        ["DeskEmptyDayTitle"] = "Nothing written on this day yet",
        ["DeskEmptyDayBody"] = "Create a note to start this day's first entry.",
        ["DeskEmptyDayButtonFormat"] = "New note · {0}",
        ["DeskLoadMore"] = "Show more",
        ["DeskTodoOpenFormat"] = "{0} open",
        ["DeskCountFormat"] = "{0}",
        ["DeskFilesDropFormat"] = "Drop files here, or click, to keep them on {0}",
        ["DeskFileDelete"] = "Delete",
        ["DeskDayTodoTitle"] = "To-dos for this day",
        ["DeskDayTodoEmptySuffix"] = " to add one to this day.",
        ["DeskDayTodoNone"] = "No to-dos",
        ["DeskFilesAdd"] = "+ Add",
        ["DeskFilesEmpty"] = "No files kept for this day.",
        ["DeskPalettePlaceholder"] = "Search notes, files and dates",
        ["DeskPaletteShortcuts"] = "Shortcuts",
        ["DeskPaletteNewNote"] = "Create a new note",
        ["DeskSettingsGeneral"] = "General",
        ["DeskSettingsShortcuts"] = "Shortcuts",
        ["DeskSettingsData"] = "Data",
        ["DeskSettingsAccount"] = "Account",
        ["DeskSettingsTheme"] = "Theme",
        ["DeskThemeLight"] = "Light",
        ["DeskThemeDark"] = "Dark",
        ["DeskThemeSwitchFormat"] = "Switch · {0}",
        ["DeskOpenFolder"] = "Open",
        ["DeskAccountManageShort"] = "Manage",
        ["DeskShortcutChangeTip"] = "Click to change",
        ["DeskAccountMenu"] = "Account menu",
        ["DeskBrandName"] = "Daynote",
        ["DeskPreviousWeek"] = "Previous week",
        ["DeskNextWeek"] = "Next week",
        ["TimelineEmpty"] = "No notes to show",

        // Note list
        ["NewNote"] = "New note",
        ["NoteCountFormat"] = "{0} notes",
        ["NoteCountFormatOne"] = "{0} note",
        ["DayNotesEmpty"] = "No notes on this date",

        // Editor
        ["TitlePlaceholder"] = "Title",
        ["Favorite"] = "Favorite",
        ["OpenStickyNote"] = "Open as a sticky note",
        ["StickyNoteWindow"] = "Sticky note",
        ["PinStickyNote"] = "Keep on top",
        ["UnpinStickyNote"] = "Stop keeping on top",
        ["CloseStickyNote"] = "Close sticky note",
        ["StickyNoteBody"] = "Sticky note body",
        ["SaveFileTitle"] = "Save a copy",
        ["SaveFileFilter"] = "{0} file|*{1}|All files|*.*",
        ["SaveFileFilterAny"] = "All files|*.*",
        ["SaveFileTip"] = "Double-click to save a copy",
        ["SaveFileDoneFormat"] = "Saved · {0}",
        ["SaveFileFailed"] = "Could not save the file",
        ["DeleteNoteTip"] = "Delete note",
        ["NoteMenuRename"] = "Rename",
        ["NoteMenuDuplicate"] = "Duplicate",
        ["NoteMenuDelete"] = "Delete",
        ["NoteDuplicateSuffix"] = " (copy)",
        ["TagAddPlaceholder"] = "+ tag",
        ["NoNoteSelected"] = "Pick a note from the list on the left, or create a new one",
        ["NoteMetaFormat"] = "{0} chars · {1} lines",
        ["NoteUpdatedFormat"] = "Edited {0}",
        ["EditorBodyPlaceholder"] = "Write your note.  Lines like '-[] task (07/25 14:00)' are added to the To-do panel automatically.",

        // Right panel tabs
        ["TabTodo"] = "To-do",
        ["TabTodoFormat"] = "To-do ({0})",
        ["TabTags"] = "Tags",
        ["TabTagsFormat"] = "Tags ({0})",
        ["TabTagsName"] = "Tags tab",
        ["TabFiles"] = "Files",
        ["TabFavoritesName"] = "Favorites tab",

        // Tags tab
        ["TagPanelEmpty"] = "Type #tags in your notes and they'll gather here.",

        // Favorites tab
        ["FavoritesPanelEmpty"] = "Star a note and it will be collected here.",
        ["FavoritesPreviewEmpty"] = "No content",

        // Todo tab
        ["TodoEmptyText"] = "(empty)",
        ["TodoEmptyPrefix"] = "Use ",
        ["TodoEmptyCode"] = "+ To-do",
        ["TodoEmptySuffix"] = " to add one and it shows up here",

        // Clipboard tab

        // Files tab
        ["AddFile"] = "Add files or images",
        ["FileTabEmpty"] = "No files kept on this date",
        ["FileAwaitingDownload"] = "Downloading",

        // Search dropdown result kinds
        ["SearchKindDate"] = "Date",
        ["SearchKindFile"] = "File",
        ["SearchFailedRow"] = "The search failed. Try typing it again.",
        ["SearchNoResultsRow"] = "No results found",
        ["SearchDateNoteCountFormat"] = "{0} notes",
        ["SearchDateNoteCountFormatOne"] = "{0} note",

        // Language (settings)
        ["SettingsLanguageRow"] = "Language",
        ["SettingsLanguageLabel"] = "Display language",
        ["SettingsLanguageDesc"] = "Your choice applies across the app right away — no restart needed.",
        ["LanguageKorean"] = "한국어",
        ["LanguageEnglish"] = "English",

        // Date patterns. These are .NET custom format strings, not prose: literal text inside a
        // pattern must stay single-quoted, and the field letters (yyyy/M/d/ddd) must survive
        // translation or the date renders wrong.
        ["DateFormatLong"] = "dddd, MMMM d, yyyy",
        ["DateFormatMonth"] = "MMMM yyyy",
        ["DateFormatDayHeading"] = "ddd, MMM d",

        // Mini-calendar weekday header, Sunday first
        ["WeekdaySun"] = "Su",
        ["WeekdayMon"] = "Mo",
        ["WeekdayTue"] = "Tu",
        ["WeekdayWed"] = "We",
        ["WeekdayThu"] = "Th",
        ["WeekdayFri"] = "Fr",
        ["WeekdaySat"] = "Sa",

        // Compact shell (narrow-window layout)
        ["CommandRegion"] = "Command region",
        ["StatusRegion"] = "Status region",
        ["CompactWorkspaceSwitch"] = "Compact workspace switcher",
        ["CompactNavigate"] = "Browse",
        ["CompactNavigateAutomation"] = "Browse view",
        ["CompactNotes"] = "Notes",
        ["CompactNotesAutomation"] = "Notes view",
        ["CalendarWeekdayHeader"] = "Calendar weekday header",
        ["CalendarDays"] = "Calendar days",

        // Default display title for a note the user never named ({0} = note number)
        ["UntitledNoteFormat"] = "Note {0}",

        // Cloud sync: account section and the command-row status chip
        ["CloudSyncTitle"] = "Cloud sync",
        ["CloudSyncBlurb"] = "Optional. Sign in with Google and your notes sync to your other devices. By default the server holds the key that opens them, so whoever runs the service can read what is stored — turn on the lock below and it cannot.",
        ["CloudSyncPrivacyNote"] = "The server stores your note bodies, titles, tags, and dates encrypted, and holds the key to that encryption. Your Google or Apple account id and email address are stored to identify the account.",
        ["CloudSyncLocalNote"] = "The database on this PC stays unencrypted, and sync is not a substitute for a backup. What syncs today is notes, to-dos, tags and favorites; image and file sync is still being built.",
        ["AccountSignInWithGoogle"] = "Sign in with Google",
        ["AccountSignInWithApple"] = "Sign in with Apple",
        ["AccountDelete"] = "Delete account",
        ["AccountDeleteTitle"] = "Delete your Daynote account?",
        ["AccountDeleteBody"] = "This deletes the account and everything the sync service holds for it — synced notes, files and sign-ins on every device — immediately and for good. The notes on this device stay here. It cannot be undone.",
        ["AccountDeleteConfirm"] = "Delete permanently",
        ["AccountDeleteCancel"] = "Keep my account",
        ["AccountDeleted"] = "Your account was deleted. Your notes are still on this device.",
        ["AccountDeletedSessionGone"] = "You are signed out. If you had asked to delete the account, it is already gone — sign in again to check. Your notes are still on this device.",
        ["AccountSessionEnded"] = "Your session ended. Please sign in again. Your notes are still on this device.",
        ["BillingLoadFailed"] = "Could not load your subscription.",
        ["ProfileMoveTitle"] = "Move this device's notes to this account?",
        ["ProfileMoveBodyFormat"] = "There are {0} notes written on this device without an account. Moving them syncs them to this account and takes them out of this device's signed-out notes. Keeping them here uploads nothing, and they are back as they were when you sign out.",
        ["ProfileMoveBodyFormatOne"] = "There is {0} note written on this device without an account. Moving it syncs it to this account and takes it out of this device's signed-out notes. Keeping it here uploads nothing, and it is back as it was when you sign out.",
        ["ProfileMoveFilesFormat"] = "{0} attached files go with them.",
        ["ProfileMoveFilesFormatOne"] = "{0} attached file goes with them.",
        ["ProfileMoveConfirm"] = "Move them",
        ["ProfileMoveKeep"] = "Keep them on this device only",
        ["ProfileSwitching"] = "Switching note stores…",
        ["SignOutChoiceTitle"] = "Sign out?",
        ["SignOutChoiceBody"] = "Keeping this account's notes on this device opens them straight away when you sign back in. On a shared device, remove them. Notes already synced to the cloud stay there either way.",
        ["SignOutUnsyncedFormat"] = "{0} changes have not synced yet. If you sign out now, they stay only on this device.",
        ["SignOutUnsyncedFormatOne"] = "{0} change has not synced yet. If you sign out now, it stays only on this device.",
        ["SignOutKeep"] = "Sign out and keep notes here",
        ["SignOutRemove"] = "Sign out and remove them from this device",
        ["SignOutCancel"] = "Stay signed in",
        ["SignOutRemoveUnsyncedFormat"] = "The {0} unsynced changes will be gone everywhere. Remove anyway?",
        ["SignOutRemoveUnsyncedFormatOne"] = "The {0} unsynced change will be gone everywhere. Remove anyway?",
        ["SignOutRemoveConfirm"] = "Discard them and remove",
        ["DeletedNotesTitle"] = "What should happen to the notes on this device?",
        ["DeletedNotesBody"] = "Your account was deleted. Its notes can stay on this device as notes that need no account, or be removed from this device too.",
        ["DeletedNotesBodySessionGone"] = "You are signed out. If you had asked to delete the account, it is already gone. Its notes can stay on this device as notes that need no account, or be removed from this device too.",
        ["DeletedNotesKeep"] = "Keep them as local notes",
        ["DeletedNotesRemove"] = "Remove them from this device",
        ["DeletedNotesRemoveBody"] = "The account is already deleted, so the notes on this device are the only copy left. Removing them cannot be undone.",
        ["DeletedNotesRemoveBodySessionGone"] = "The notes on this device may be the only copy left. Even if the account still exists, any changes that did not sync go with them. Removing them cannot be undone.",
        ["DeletedNotesRemoveConfirm"] = "Remove them for good",
        ["DeletedNotesRemoveCancel"] = "Don't remove",
        ["ProfileErrorUnsaved"] = "The open note could not be saved, so nothing was changed. Check the note and try again.",
        ["ProfileErrorOwnerMismatch"] = "This account's notes on this device are recorded as belonging to another account, so syncing stopped. Go back to your local notes, or sign in with another account.",
        ["ProfileLeaveMismatched"] = "Go back to local notes",
        ["ProfileSwitchStalled"] = "The open note could not be saved, so the switch did not finish. Daynote opens the new note store the next time it starts.",
        ["ProfileSwitchRetry"] = "Switch now",
        ["ProfileSwitchFailedScreen"] = "The note store could not be opened. Close the app completely and open it again. Your notes are still on this device.",
        ["AccountErrorUnexpected"] = "Something unexpected stopped this from finishing. Try again.",
        ["AccountErrorProfile"] = "Could not switch this device's note store. Try again.",
        ["AccountAppleFallbackName"] = "Apple Account",
        ["AccountAppleOnlyNote"] = "Apple sign-in works on iPhone and iPad only. To use Daynote on your computer too, sign in with Google.",
        ["AccountErrorSubscriptionActive"] = "A paid subscription is still running on this account. Cancel it first — from the link in your payment receipt email, or in Daynote on your computer — then delete the account.",
        ["AccountSignInBrowserHint"] = "Your browser will open so you can sign in with Google. Daynote never sees or stores your password.",
        ["AccountKeyMissingBlurb"] = "This PC has no key to open your notes. You are still signed in, so it only needs fetching again.",
        ["AccountKeyMissingBlurbMobile"] = "This device has no key to open your notes. You are still signed in, so it only needs fetching again.",
        ["AccountRestoreKey"] = "Fetch the key again",
        ["AccountErrorSignInCancelled"] = "The sign-in was not completed. Try again when you are ready.",
        ["AccountErrorUnverifiedIdentity"] = "This Google account has no verified email address, so it cannot be used to sign in.",
        ["AccountLockTitle"] = "Lock your notes (end-to-end encryption)",
        ["AccountLockBlurb"] = "Turning the lock on encrypts your notes with a passphrase, so nobody running the service can read them. In exchange, you enter that passphrase once on every new PC.",
        ["AccountLockBlurbMobile"] = "Turning the lock on encrypts your notes with a passphrase, so nobody running the service can read them. In exchange, you enter that passphrase once on every new device.",
        ["AccountLockOn"] = "On — the notes in this account cannot be opened on the server.",
        ["AccountLockOff"] = "Off — whoever runs the service can read your note content.",
        ["AccountLockEnable"] = "Turn the lock on",
        ["AccountLockDisable"] = "Turn the lock off",
        ["AccountLockConfirm"] = "Lock",
        ["AccountLockCancel"] = "Cancel",
        ["AccountPassphrase"] = "Lock passphrase",
        ["AccountPassphraseHint"] = "Use at least {0} characters. If you forget it, your recovery key is the only way back in.",
        ["AccountUnlockTitle"] = "Unlock your notes",
        ["AccountUnlockBlurb"] = "This account is locked. Enter its passphrase to open your notes on this PC. The notes already on this PC are untouched.",
        ["AccountUnlockBlurbMobile"] = "This account is locked. Enter its passphrase to open your notes on this device. The notes already on this device are untouched.",
        ["AccountUnlock"] = "Unlock",
        ["AccountUseRecoveryKey"] = "Use the recovery key instead",
        ["AccountUsePassphrase"] = "Use the passphrase instead",
        ["AccountRecoveryKeyLabel"] = "Recovery key",
        ["AccountLockedTitle"] = "Your notes are locked",
        ["RecoveryKeyTitle"] = "Recovery key",
        ["RecoveryKeyBlurb"] = "Write this down somewhere safe. It is the only way to recover the notes in your cloud copy if you forget the lock passphrase, and it cannot be shown again.",
        ["RecoveryKeyCopy"] = "Copy",
        ["RecoveryKeyCopied"] = "Copied",
        ["RecoveryKeySaveToFile"] = "Save to file",
        ["RecoveryKeyConfirm"] = "I have saved my recovery key",
        ["RecoveryKeyDone"] = "Done",
        ["RecoveryKeyFileFilter"] = "Text file (*.txt)|*.txt",
        ["AccountErrorInvalidPassphrase"] = "That lock passphrase is incorrect.",
        ["AccountErrorInvalidRecoveryKey"] = "That is not this account’s recovery key.",
        ["AccountErrorLockedOut"] = "This PC cannot open your notes. Enter the lock passphrase or your recovery key.",
        ["AccountErrorWeakPassphrase"] = "Use at least {0} characters.",
        ["AccountErrorUnsupportedVersion"] = "This account was locked by a newer version of Daynote. Update the app.",
        ["BillingTitle"] = "Subscription",
        ["BillingBlurb"] = "Real-time sync of notes and to-dos is free. Syncing images and files is the Pro subscription; Daynote itself, and the notes and files on this PC, keep working either way.",
        ["BillingTrialFormat"] = "{0} days left in your free trial.",
        ["BillingTrialFormatOne"] = "{0} day left in your free trial.",
        ["BillingActive"] = "Subscribed.",
        ["BillingActiveFormat"] = "Subscribed. Renews on {0}.",
        ["BillingGraceFormat"] = "We could not take your payment. Please check your payment method within {0} days.",
        ["BillingTrialOver"] = "Your trial has ended. Notes keep syncing; subscribe to sync images and files again.",
        ["BillingExpired"] = "Your subscription ended, so image and file sync has stopped. Notes keep syncing, and the files you already uploaded are kept.",
        ["BillingSubscribe"] = "Subscribe",
        ["BillingRenew"] = "Renew subscription",
        ["BillingSubscribeAnnual"] = "Subscribe yearly · $19.99 / year",
        ["BillingSubscribeMonthly"] = "Monthly · $2.49 / month",
        ["BillingManage"] = "Manage subscription",
        ["BillingLapseNote"] = "Nothing is deleted when file sync stops. Notes keep syncing, the files on this PC are untouched, and your cloud copy is kept — resubscribe and it picks up where it left off.",
        ["BillingNoSaleBannerBody"] = "Your notes keep syncing. The files on this PC and anything already uploaded are kept.",
        ["BillingNoSaleBannerBodyPhone"] = "Your notes keep syncing. The files on this device and anything already uploaded are kept.",
        ["SyncChipFilesOff"] = "Files not synced",
        ["BillingBrowserHint"] = "Payment happens in your browser. Card details are handled by the payment provider; Daynote never stores them.",
        ["SyncChipUnpaid"] = "Files: subscription needed",
        ["AccountSignOut"] = "Sign out",
        ["AccountSyncNow"] = "Sync now",
        ["AccountBarSignIn"] = "Sign in",
        ["AccountBarLocal"] = "Saved on this PC",
        ["AccountBusy"] = "Working…",
        // {0} = the signed-in email address.
        ["AccountSignedInAsFormat"] = "Signed in as {0}",
        // {0} = a formatted local time.
        ["AccountLastSyncFormat"] = "Last synced {0}",
        ["AccountNeverSynced"] = "Not synced yet",
        // {0} = number of notes replaced by a newer version from another device.
        ["AccountConflictsFormat"] = "{0} notes were replaced by a newer version from another device. The earlier text was kept as a copy.",
        ["AccountConflictsFormatOne"] = "{0} note was replaced by a newer version from another device. The earlier text was kept as a copy.",
        ["AccountOpenConflicts"] = "Open the copies folder",
        ["SyncChipSynced"] = "Synced",
        ["SyncChipSyncing"] = "Syncing",
        ["SyncChipPending"] = "Pending",
        ["SyncChipOffline"] = "Offline",
        ["SyncChipLocked"] = "Locked",
        ["SyncChipError"] = "Sync problem",
        ["SyncStatusAutomation"] = "Cloud sync status",
        ["AccountErrorInvalidCredentials"] = "That sign-in is no longer valid. Sign in again.",
        ["AccountErrorOffline"] = "Daynote could not reach the sync service. Check your connection and try again.",
        ["AccountErrorServer"] = "The sync service reported a problem. Try again in a moment.",


        // Account window (docs/design-renewal/Daynote Account.dc.html)
        ["AccountWindowTitle"] = "Daynote account",
        ["AccountMenuAutomation"] = "Account",
        ["AccountManage"] = "Account & subscription",
        ["AccountAvatarTooltipFormat"] = "{0} · {1} · {2}",
        ["AccountSignInTitle"] = "Sign in to Daynote",
        ["AccountSignInLead"] = "Your notes stay on this PC either way. Signing in is only for seeing the same notes on more than one device.",
        ["AccountSignInTerms"] = "Continuing means you accept the terms of service and the privacy policy.",
        ["AccountTerms"] = "Terms of service",
        ["AccountPrivacy"] = "Privacy policy",
        ["AccountSkipSignIn"] = "Keep using Daynote without an account",
        ["AccountPerkSyncTitle"] = "Sync across devices",
        ["AccountPerkSyncDesc"] = "The same notes on your laptop and desktop",
        ["AccountPerkLockTitle"] = "Note lock",
        ["AccountPerkLockDesc"] = "Turn it on and the server cannot read them either",
        ["AccountPerkExportTitle"] = "Export anytime",
        ["AccountPerkExportDesc"] = "Save everything as a backup file",
        ["AccountPlanFree"] = "Free",
        ["AccountPlanTrial"] = "Trial",
        ["AccountPlanPro"] = "Pro",
        ["AccountPlanGrace"] = "Payment pending",
        ["BillingTrialBannerTitleFormat"] = "{0} days left in your trial",
        ["BillingTrialBannerTitleFormatOne"] = "{0} day left in your trial",
        ["BillingTrialBannerBody"] = "Subscribe to Pro or Premium before the trial ends and image and file sync carries on without a break. If it does stop, notes keep syncing and your files stay where they are.",
        ["BillingGraceBannerTitle"] = "A payment did not go through",
        ["BillingGraceBannerBodyFormat"] = "Please check your payment method within {0} days. File sync keeps working until then.",
        ["BillingExpiredBannerTitle"] = "Image and file sync has stopped",
        ["BillingUpgradeTitle"] = "Upgrade",
        ["BillingPlanMonthly"] = "Monthly",
        ["BillingPlanAnnual"] = "Yearly",
        ["BillingPriceMonthly"] = "$2.49",
        ["BillingPriceAnnual"] = "$19.99",
        ["BillingPriceUnitMonthly"] = "/ month",
        ["BillingPriceUnitAnnual"] = "/ year",
        ["BillingPriceSubMonthly"] = "Billed monthly · cancel anytime",
        ["BillingPriceSubAnnual"] = "About $1.67 a month · billed once a year",
        // The plan table (Daynote Desktop B): what the two plans are, side by side. Every row
        // is something stated elsewhere already — the sync blurb, what signing in buys, the
        // server's own attachment quota — because a comparison that promises what the product
        // does not do is worse than no comparison.
        ["PlanTableTitle"] = "Plans",
        ["PlanFreeName"] = "Free",
        ["PlanFreePrice"] = "₩0",
        ["PlanFreeNote"] = "Always free",
        ["PlanProName"] = "Pro",
        ["PlanProNote"] = "Annual",
        ["PlanCurrent"] = "Current plan",
        ["PlanCompare"] = "Compare plans",
        ["PlanRowNotes"] = "Note and to-do sync",
        ["PlanRowDevices"] = "Sync across devices",
        ["PlanRowLock"] = "Note lock",
        ["PlanRowExport"] = "Export any time",
        ["PlanRowFiles"] = "Image and file sync",
        ["AccountPlanPremium"] = "Premium",
        ["PlanPremiumName"] = "Premium",
        ["PlanRowStorage"] = "File storage",
        ["PlanStoragePro"] = "2GB",
        ["PlanStorageUnlimited"] = "Unlimited",
        ["PlanFairUseNote"] = "Unlimited within fair use",
        ["PlanPerMonthly"] = "Monthly",
        ["PlanPerAnnualFormat"] = "Annual · about {0}/mo",
        ["PlanInUse"] = "Current",
        ["PlanSelect"] = "Choose",
        ["PlanChange"] = "Switch",
        ["PlanAfterTrial"] = "After the trial",
        ["BillingSavingFormat"] = "Save {0}%",
        ["BillingSubscribedFormat"] = "Subscribed to {0}",
        ["BillingSubscribedDetailFormat"] = "Next payment {0} · {1}",
        ["BillingPricePerMonthFormat"] = "{0} / month",
        ["BillingPricePerYearFormat"] = "{0} / year",
        ["BillingChangeToPremium"] = "Switch to Premium",
        ["BillingCancel"] = "Cancel subscription",
        ["AccountPlanSubRenewsFormat"] = "{0} · renews {1}",
        ["StorageLabel"] = "Storage",
        ["StorageUsageFormat"] = "{0} / {1}",
        ["StorageUsedFormat"] = "{0} used",
        ["CheckoutTitle"] = "Subscribe",
        ["CheckoutChangeTitle"] = "Change plan",
        ["CheckoutTierProSub"] = "File sync, 2GB",
        ["CheckoutTierPremiumSub"] = "Unlimited file sync",
        ["CheckoutMonthlySub"] = "Billed monthly",
        ["CheckoutAnnualSub"] = "Billed once a year",
        ["CheckoutPlanLabelFormat"] = "{0} · {1}",
        ["CheckoutStartRow"] = "Starts",
        ["CheckoutRenewRow"] = "Renews",
        ["CheckoutTodayRow"] = "Due today",
        ["CheckoutChangeNote"] = "The difference for the rest of the period is charged today, or credited against your next payment.",
        ["CheckoutFinePrint"] = "You can cancel any time in Settings › Account. After cancelling, you keep access until the end of the period.",
        ["CheckoutCancel"] = "Cancel",
        ["CheckoutPayFormat"] = "Pay {0}",
        ["CheckoutChangeConfirm"] = "Change plan",
        ["CheckoutWaitingTitle"] = "Finish paying in your browser",
        ["CheckoutWaitingBody"] = "Paddle's checkout opened in your browser. This window updates by itself once the payment goes through.",
        ["CheckoutReopen"] = "Open checkout again",
        ["CheckoutDoneTitleFormat"] = "Your {0} subscription has started",
        ["CheckoutChangedTitleFormat"] = "You're now on {0}",
        ["CheckoutDoneBody"] = "Image and file sync keeps running.\nPaddle emails the receipt to the address used at checkout.",
        ["CheckoutDoneOk"] = "OK",
        ["BillingDuplicateNote"] = "A second subscription was paid for. Only the first is used and the other will be refunded; let us know from Manage subscription or by support email.",
        ["BillingAnnualSaving"] = "Save 33%",
        ["BillingFeatureSync"] = "Images and files synced across all your devices",
        ["BillingFeatureQuota"] = "Attachments kept in the cloud",
        ["BillingCheckoutFormat"] = "Subscribe to {0} · {1}",
        ["BillingProviderNote"] = "Paddle handles payment and tax as the merchant of record · cancel anytime",
        ["BillingDetailTitle"] = "Subscription",
        ["BillingRowPlan"] = "Plan",
        ["BillingRowState"] = "Status",
        ["BillingRowRenews"] = "Next payment",
        ["BillingRowEnds"] = "Access until",
        ["BillingStateActive"] = "Active",
        ["BillingStateTrial"] = "Trial",
        ["BillingStateGrace"] = "Payment failed · retrying",
        ["BillingPortalNote"] = "Changing your card, cancelling, and finding receipts happen on the Paddle portal. Switch plans from the plan table.",
        ["AccountVersionFormat"] = "Daynote {0}",
        ["AccountSyncState"] = "Cloud sync",

        // Site paths (joined onto the sync service origin; language-specific)
        ["AccountTermsUrl"] = "/en/terms/",
        ["AccountPrivacyUrl"] = "/privacy",

        // ── Mobile ───────────────────────────────────────────────────────────────────────────────
        // The phone's bottom bar. The first tab reuses "Today", which is the action it performs.
        ["TabSearch"] = "Search",
        ["TabLists"] = "Lists",
        // The floating helpers over the note body: they type the syntax a thumb would otherwise
        // have to hunt for two keyboard layers down.
        ["InsertDate"] = "Date",
        ["InsertTime"] = "Time",
        // The segmented control on the Lists page. The desktop's TabTodoName and friends end in
        // "tab" because there they name a tab in a tooltip; as segment labels they read as noise.
        ["SegmentTodo"] = "To-do",
        ["SegmentFavorites"] = "Favorites",
        ["SegmentTags"] = "Tags",
        // The desktop says "Stored on this PC only", which is wrong on a phone.
        ["AccountBarLocalMobile"] = "Stored on this device only",
        // The account card on a phone. The desktop copy says "PC" and names a laptop and a desktop,
        // which is the wrong half of the sentence to read on the device you are holding.
        ["AccountSignInLeadMobile"] = "Your notes stay on this device either way. Signing in is only for seeing the same notes on your phone and your computer.",
        ["AccountPerkSyncDescMobile"] = "The same notes on your phone and your computer",
        ["Back"] = "Back",
        ["PreviousDay"] = "Previous day",
        ["NextDay"] = "Next day",
        // In-App Purchase on the iPhone (docs/CLOUD_SYNC.md §14.8): the plans page, and the
        // disclosure App Store guideline 3.1.2 wants beside the buy button. Only the iPhone shows these.
        ["AccountDeleteAppStoreNote"] = "Deleting the account does not cancel an App Store subscription. Cancel it separately in Settings › Apple ID › Subscriptions.",
        ["BillingAppStoreManaged"] = "Subscribed through the App Store · managed in iPhone Settings",

        // To-do reminders (phone)
        ["ReminderSettingsSection"] = "Notifications",
        ["ReminderSettingsTitle"] = "To-do reminders",
        ["ReminderSettingsHint"] = "Reminds you when a to-do with a due date is due",
        ["ReminderSettingsDenied"] = "Daynote notifications are turned off in system settings",
        ["ReminderSettingsOpenSystem"] = "Open notification settings",
        ["ReminderChannelName"] = "To-do reminders",
        ["ReminderActionDone"] = "Done",
        ["ReminderActionSnooze"] = "In 30 min",
        ["ReminderChannelDescription"] = "Reminds you when a to-do in your notes is due.",
        ["ReminderTimeTitle"] = "Default reminder time",
        ["ReminderTimeHint"] = "When a to-do with a date but no time reminds you",
        ["ReminderTimeHour"] = "Hour",
        ["ReminderTimeMinute"] = "Minute",
        ["ReminderTimeDone"] = "Done",
        ["ReminderPreciseTitle"] = "Precise reminders",
        ["ReminderPreciseHint"] = "Without it, reminders can arrive up to an hour late",
        ["ReminderBodyFormat"] = "{0} · {1}",

        // The @ command's readback (docs/TODOS.md §7), worded as the design mocks show it.
        // The punctuation and the ordering live here rather than in code: Korean joins a date
        // to a time with a space and says the meridiem first, English joins with "·" and says
        // it last. Each language also declares how it formats the two ends of a time range,
        // so "오후 3:00–4:00" and "3:00–4:00 PM" come out of one join with the same two
        // arguments — which keeps the placeholders identical across the pair, as every other
        // format here is. The patterns at the end are .NET date and time formats, translated
        // because the order of month and day is not universal either.
        ["AgendaPhraseEmpty"] = "Type a date, time or repeat",
        ["AgendaPhraseEmptyPickable"] = "Type or pick a date, time or repeat",
        ["AgendaPhraseExampleToday"] = "today",
        ["AgendaPhraseExampleTomorrow"] = "tomorrow",
        ["AgendaPhraseExampleWeekdayTime"] = "fri 3pm",
        ["AgendaPhraseExampleRepeat"] = "every mon",
        ["AgendaReadbackDue"] = "Due {0}",
        ["AgendaReadbackAllDay"] = "{0} · All day",
        ["AgendaReadbackDateAtTime"] = "{0} at {1}",
        ["AgendaReadbackDateAndRange"] = "{0} · {1}",
        ["AgendaReadbackAtTime"] = "{0} at {1}",
        ["AgendaReadbackRange"] = "{0}–{1}",
        ["AgendaReadbackRangeShort"] = "{0}–{1}",
        ["AgendaReadbackEveryDay"] = "Every day",
        ["AgendaReadbackEveryWeekday"] = "Every {0}",
        ["AgendaReadbackTomorrowPrefix"] = "Tomorrow, {0}",
        ["AgendaReadbackRolledNote"] = "{0} has passed, so this reads as tomorrow. Type ‘{1}’ for tonight.",
        ["AgendaReadbackRolledNoteShort"] = "{0} has passed, so this reads as tomorrow. Type ‘{1}’.",
        ["AgendaReadbackDateLong"] = "ddd, MMM d",
        ["AgendaReadbackDateLongPrefixed"] = "ddd MMM d",
        ["AgendaReadbackDateShort"] = "MMM d",
        ["AgendaReadbackWeekday"] = "ddd",
        ["AgendaReadbackTime"] = "h:mm tt",
        ["AgendaReadbackHour"] = "h tt",
        ["AgendaReadbackRangeStart"] = "h:mm",
        ["AgendaReadbackRangeEnd"] = "h:mm tt",
        ["AgendaReadbackRangeStartHour"] = "%h",
        ["AgendaReadbackRangeEndHour"] = "h tt",
        ["AgendaReadbackEveningHint"] = "h'pm'",

        // The @ popup itself (docs/design-renewal/… 01 - Command).
        ["AgendaCaptureTask"] = "To-do",
        ["AgendaCaptureEvent"] = "Event",
        ["AgendaCaptureKeyHints"] = "Enter Create · Tab Switch type · Esc Cancel",

        // What a recurrence rule is called (design §06 6i/6j). Short labels for a row or a
        // card; the @ popup's readback is a sentence and lives above. These name rules this
        // build cannot schedule as well as ones it can, because the unsupported-alert notice
        // puts the name in its sentence.
        ["AgendaRuleDaily"] = "Daily",
        ["AgendaRuleEveryNDays"] = "Every {0} days",
        ["AgendaRuleWeekly"] = "Weekly",
        ["AgendaRuleWeeklyOn"] = "Weekly on {0}",
        ["AgendaRuleEveryNWeeks"] = "Every {0} weeks",
        ["AgendaRuleEveryNWeeksOn"] = "Every {0} weeks on {1}",
        ["AgendaRuleMonthly"] = "Monthly",
        ["AgendaRuleMonthlyOnDay"] = "Monthly on the {0}th",
        ["AgendaRuleMonthlyOnNthWeekday"] = "Monthly on the {0} {1}",
        ["AgendaRuleYearly"] = "Yearly",
        ["AgendaRuleRepeats"] = "Repeats",
        ["AgendaRuleDayJoin"] = ", ",
        ["AgendaRuleOrdinalLast"] = "last",
        ["AgendaRuleOrdinal1"] = "first",
        ["AgendaRuleOrdinal2"] = "second",
        ["AgendaRuleOrdinal3"] = "third",
        ["AgendaRuleOrdinal4"] = "fourth",
        ["AgendaRuleOrdinalN"] = "{0}th",
        ["AgendaRuleNoAlerts"] = "Alerts aren’t available for this repeat ({0}) yet. Daily and weekly repeats send alerts.",

        // A to-do row's "when" (design §04). .NET date and time patterns, translated
        // because the order of month and day is not universal.
        ["TodoRowTimeFormat"] = "HH:mm",
        ["TodoRowDateTimeFormat"] = "M/d HH:mm",
        ["TodoRowDateFormat"] = "M/d",

        ["DeskDayTodoRemainingFormat"] = "{0} left",
        ["DeskDayTodoDoneFormat"] = "Done {0}",

        // The built-in to-do list stores no name, so that it reads in whichever language
        // the app is in. A rename writes a real one and it stops being translated.
        ["AgendaListDefaultName"] = "My tasks",

        ["AgendaListNew"] = "+ New list",
        ["AgendaListRename"] = "Rename",
        ["AgendaListDelete"] = "Delete list",
        ["AgendaListNewName"] = "New list",

        // The menu bar popover and the tray flyout (menu bar design §01).
        ["MenuBarHeaderFormat"] = "'Today · 'ddd, MMM d",
        ["MenuBarModeTodo"] = "To-do",
        ["MenuBarModeNote"] = "Note",
        ["MenuBarTodoPlaceholder"] = "A to-do for today…",
        ["MenuBarNotePlaceholder"] = "A line for today’s note…",
        ["MenuBarTodoHint"] = "Enter: add to today’s to-dos",
        ["MenuBarMore"] = "More…",
        ["MenuBarAppendHintFormat"] = "Enter: append to today’s note · {0}: new note",
        ["MenuBarUpNext"] = "Up next",
        ["MenuBarTodosFormat"] = "To-dos · {0} left",
        ["MenuBarTodosEmpty"] = "Nothing left for today",
        ["MenuBarJustNow"] = "Just now",
        ["MenuBarAddedToFormat"] = "Added to {0}",
        ["MenuBarNoticeDateFormat"] = "MMM d",
        ["MenuBarAppended"] = "Added to today’s note",
        ["MenuBarAppendedNewNote"] = "Added to a new note for today",
        ["MenuBarAppendFailed"] = "Couldn’t add to the note. Try again.",
        ["MenuBarSaveFailed"] = "Couldn’t save it. Try again.",
        ["MenuBarView"] = "View",
        ["MenuBarOpenApp"] = "Open Daynote",
        ["MenuBarSettings"] = "Settings",
        ["MenuBarEventInFormat"] = "in {0}",
        ["MenuBarEventNow"] = "Now",
        ["MenuBarHoursMinutesFormat"] = "{0} h {1} min",
        ["MenuBarHoursFormat"] = "{0} h",
        ["MenuBarMinutesFormat"] = "{0} min",
        ["MenuBarStatusTooltipFormat"] = "Daynote · {0} to-dos left today",
        ["SettingsMenuBarLabel"] = "Show in menu bar",
        ["SettingsMenuBarDesc"] = "Shows how many to-dos are left today; click it for quick capture. Daynote stays in the menu bar when the window is closed.",
        ["SettingsCaptureHotkeyLabel"] = "Quick capture",
        ["SettingsCaptureHotkeyNone"] = "Not set",
        ["SettingsCaptureHotkeyDesc"] = "Opens quick capture from anywhere. Change it if another app uses it.",

        // The to-do sheet (phone) and the add-to-do card (desktop): one draft, TodoEntryViewModel.
        ["TodoEntryTaskPlaceholder"] = "What needs doing?",
        ["TodoEntryEventPlaceholder"] = "What's happening?",
        ["TodoEntryTitle"] = "Title",
        ["TodoEntryNotes"] = "Notes",
        ["TodoEntryNotesPlaceholder"] = "Notes (optional)",
        ["TodoEntryRepeat"] = "Repeat",
        ["TodoEntryRepeatNone"] = "Never",
        ["TodoEntryRepeatDaily"] = "Daily",
        ["TodoEntryRepeatWeekdays"] = "Weekdays",
        ["TodoEntryRepeatWeekly"] = "Weekly",
        ["TodoEntryRepeatMonthly"] = "Monthly",
        ["TodoEntryRepeatYearly"] = "Yearly",
        ["TodoEntryRepeatWeeklyOn"] = "Every {0}",
        ["TodoEntryRepeatMonthlyOn"] = "Monthly on day {0}",
        ["TodoEntryRepeatYearlyOn"] = "Every year on {0}",
        ["TodoEntryRepeatYearlyFormat"] = "MMM d",
        ["TodoEntryRepeatNeedsDate"] = "Pick a date to repeat",
        ["TodoEntryDate"] = "Date",
        ["TodoEntryNoDate"] = "No date",
        ["TodoEntryDateFormat"] = "ddd, MMM d",
        ["TodoEntryTime"] = "Time",
        ["TodoEntryNoTime"] = "No time",
        ["TodoEntryStart"] = "Starts",
        ["TodoEntryEnd"] = "Ends",
        ["TodoEntryList"] = "List",
        ["TodoEntryAdd"] = "Add",
        ["TodoEntryCancel"] = "Cancel",
        ["TodoAddButton"] = "+ To-do",
        ["TodoAddTitle"] = "New to-do",
        ["TodoEditTitle"] = "Edit to-do",
        ["TodoEditSave"] = "Save",
        ["TodoRowEdit"] = "Edit",
        ["TodoRowDelete"] = "Delete",
        ["TodoDeleted"] = "Deleted",
        ["TodoUndo"] = "Undo",
        ["TodoRepeatQuestion"] = "This is a repeating to-do",
        ["TodoRepeatDeleteThis"] = "Delete this one only",
        ["TodoRepeatDeleteAll"] = "Delete all repeats",
        ["TodoRepeatEditThis"] = "This one only",
        ["TodoRepeatEditAll"] = "All repeats",

        // File-dialog filter (pipe-delimited Win32 syntax; only the label is translated)
        ["BackupZipFilter"] = "Daynote backup (*.zip)|*.zip",
    };
}
